accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import UserLoginForm, PwdChangeForm


app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="registration/login.html",
                                                authentication_form=UserLoginForm), name='login'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.edit, name='edit'),
    path('profile/delete/', views.delete_user, name='deleteuser'),
    path('register/', views.accounts_register, name='register'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name="registration/password_change_form.html",
                                                                   form_class=PwdChangeForm), name='pwdforgot'),
    path('friendlist/', views.friendlist, name='friendlist'),
    path('sentrequest/<str:username>', views.sentrequest, name='sentrequest'),
    path('accept/<str:username>', views.accept, name='accept'),
    path('decline/<str:username>', views.decline, name='decline'),
    path('cancel/<str:username>', views.cancel, name='cancel'),
]

music/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('account/', include('django.contrib.auth.urls')),
    path('recommender/', include('recommender.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.core.exceptions import ValidationError
from django.core.files.images import get_image_dimensions
from django.conf import settings
from django.utils import timezone


def user_directory_path(instance, filename):
    return 'users/avatars/{0}/{1}'.format(instance.user.id, filename)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(
    upload_to=user_directory_path, default='user/avatar.jpg')
    bio = models.TextField(max_length=500, blank=True)


    def clean(self):
        if not self.avatar:
            raise ValidationError("x")
        else:
            w, h = get_image_dimensions(self.avatar)
            if w != 200:
                raise ValidationError("x")
            if h != 200:
                raise ValidationError("x")

    def __str__(self):
        return self.user.username


@ receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


class FriendList(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user')
    friends = models.ManyToManyField(User, blank=True, related_name="friends")

    def __str__(self):
        return self.user.username

    def add_friend(self, account):
        if not account in self.friends.all():
            self.friends.add(account)
            self.save()

    def remove_friend(self, account):
        if account in self.friends.all():
            self.friends.remove(account)
            self.save()

    def unfriend(self, removee):
        remover_friends_list = self
        remover_friends_list.remove_friend(removee)
        friends_list = FriendList.objects.get(user=removee)
        friends_list.remove_friend(remover_friends_list.user)

    def is_mutual(self, friend):
        if friend in self.friends.all():
            return True
        return False


class FriendRequest(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name="sender")
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name="receiver", default=True)
    is_active = models.BooleanField(blank=True, null=False, default=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.sender.username

    def accept(self):
        receiver_friend_list = FriendList.objects.get(user=self.receiver)
        if receiver_friend_list:
            receiver_friend_list.add_friend(self.sender)
            sender_friend_list = FriendList.objects.get(user=self.sender)
            if sender_friend_list:
                sender_friend_list.add_friend(self.receiver)
                self.is_active = False
                self.save()

    def decline(self):
        self.is_active = False
        self.save()

    def cancel(self):
        self.is_active = False
        self.save()

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from accounts.models import Profile

class UserLoginForm(AuthenticationForm):

    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control mb-3', 'placeholder': 'Username', 'id': 'login-username'}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Password',
            'id': 'login-pwd',
        }
    ))

class RegistrationForm(forms.ModelForm):

    username = forms.CharField(
        label='Enter Username', min_length=4, max_length=50, help_text='Required')
    email = forms.EmailField(max_length=100, help_text='Required', error_messages={
        'required': 'Sorry, you will need an email'})
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name',)

    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        r = User.objects.filter(username=username)
        if r.count():
            raise ValidationError("Username already exists")
        return username

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords do not match.')
        return cd['password2']

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError(
                'Please use another Email, that is already taken')
        return email

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'Username'})
        self.fields['email'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'E-mail', 'name': 'email', 'id': 'id_email'})
        self.fields['password'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Password'})
        self.fields['password2'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Repeat Password'})

class UserEditForm(forms.ModelForm):

    first_name = forms.CharField(
        label='Firstname', min_length=4, max_length=50, widget=forms.TextInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'Firstname', 'id': 'form-firstname'}))

    last_name = forms.CharField(
        label='Lastname', min_length=4, max_length=50, widget=forms.TextInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'Lastname', 'id': 'form-lastname'}))

    email = forms.EmailField(
        max_length=200, widget=forms.TextInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'Old Password', 'id': 'form-email'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].required = False
        self.fields['last_name'].required = False
        self.fields['email'].required = False


class PwdChangeForm(PasswordChangeForm):

    old_password = forms.CharField(
        label='Old Password', widget=forms.PasswordInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'Old Password', 'id': 'form-oldpass'}))
    new_password1 = forms.CharField(
        label='New password', widget=forms.PasswordInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'New Password', 'id': 'form-newpass'}))
    new_password2 = forms.CharField(
        label='Repeat password', widget=forms.PasswordInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'New Password', 'id': 'form-new-pass2'}))

class UserProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['bio', 'avatar']

        widgets = {
            'bio': forms.Textarea(attrs={'class': 'form-control', 'rows': '5'}),
        }

accounts/views.py
import json

from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.conf import settings
from django.contrib.auth import login
from django.contrib.auth.models import User
from .forms import RegistrationForm, UserEditForm, UserProfileForm
from .models import Profile
from django.shortcuts import get_object_or_404
from .models import *
from django.core.exceptions import ObjectDoesNotExist


def avatar(request):
    if request.user.is_authenticated:
        user = User.objects.get(username=request.user)
        avatar = Profile.objects.filter(user=user)
        context = {
            "avatar": avatar,
        }
        return context
    else:
        return {
            'NotLoggedIn': User.objects.none()}

def accounts_register(request):
    if request.method == 'POST':
        registerForm = RegistrationForm(request.POST)
        if registerForm.is_valid():
            user = registerForm.save(commit=False)
            user.email = registerForm.cleaned_data['email']
            user.set_password(registerForm.cleaned_data['password'])
            user.save()
            return redirect("/recommender/home")
    else:
        registerForm = RegistrationForm()
    return render(request, 'registration/register.html', {'form': registerForm})

@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user,
                                 data=request.POST)

        profile_form = UserProfileForm(
            request.POST, request.FILES, instance=request.user.profile)

        if profile_form.is_valid() and user_form.is_valid():
            user_form.save()
            profile_form.save()
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = UserProfileForm(instance=request.user.profile)

    return render(request,
                  'accounts/update.html',
                  {'user_form': user_form, 'profile_form': profile_form})

@login_required
def delete_user(request):
    if request.method == 'POST':
        user = User.objects.get(username=request.user)
        user.is_active = False
        user.save()
        return redirect('accounts:login')

    return render(request, 'accounts/delete.html')

def friendlist(request):
    userfriends = FriendList.objects.filter(user=request.user)
    friends = []
    if userfriends:
        for userfriend in userfriends:
            friends = userfriend.friends.all()
    friendrequest = FriendRequest.objects.filter(sender=request.user)
    recfriendrequest = FriendRequest.objects.filter(receiver=request.user)
    return render(request, 'accounts/friendlist.html', {'friends': friends, 'friendrequest':friendrequest, 'recfriendrequest':recfriendrequest})

@login_required
def profile(request):
    userfriends = FriendList.objects.filter(user=request.user)
    friends = []
    if userfriends:
        for userfriend in userfriends:
            friends = userfriend.friends.all()

    numfriends = len(friends)
    return render(request,
                  'accounts/profile.html',
                  {'section': 'profile',
                   'friends': friends,
                   'numfriends': numfriends})


def sentrequest(request, username):
    friendrequest = FriendRequest.objects.filter(sender=request.user)
    user = get_object_or_404(User, username=username)
    newfriend = 1
    for req in friendrequest:
        if req.receiver == user:
            newfriend = 0
    if newfriend:
        newfriendrequest = FriendRequest()
        newfriendrequest.sender = request.user
        newfriendrequest.receiver = user
        newfriendrequest.save()
    userfriends = FriendList.objects.filter(user=request.user)
    friends = []
    if userfriends:
        for userfriend in userfriends:
            friends = userfriend.friends.all()
    friendrequest = FriendRequest.objects.filter(sender=request.user)
    recfriendrequest = FriendRequest.objects.filter(receiver=request.user)
    return render(request, 'accounts/friendlist.html', {'friends': friends, 'friendrequest':friendrequest, 'recfriendrequest':recfriendrequest})

def lookup_friendslist(user):
    try:
        friendlist = FriendList.objects.get(user=user)
        return friendlist
    except ObjectDoesNotExist:
        return None

def accept(request, username):
    userid = User.objects.get(username=username)
    friend_request = FriendRequest.objects.get(sender= userid, receiver=request.user)
    if friend_request:
        friend_request.delete()

    userfriends = lookup_friendslist(request.user)
    if not userfriends:
        userfriends = FriendList()
        userfriends.user = request.user
        userfriends.save()
    userfriends.friends.add(userid)
    userfriends.save()

    otheruserfriends = lookup_friendslist(userid)
    if not otheruserfriends:
        otheruserfriends = FriendList()
        otheruserfriends.user = userid
        otheruserfriends.save()
    otheruserfriends.friends.add(request.user)
    otheruserfriends.save()

    userfriends = FriendList.objects.filter(user=request.user)
    friends = []
    if userfriends:
        for userfriend in userfriends:
            friends = userfriend.friends.all()
    friendrequest = FriendRequest.objects.filter(sender=request.user)
    recfriendrequest = FriendRequest.objects.filter(receiver=request.user)
    return render(request, 'accounts/friendlist.html', {'friends': friends, 'friendrequest':friendrequest, 'recfriendrequest':recfriendrequest})


def decline(request, username):
    userid = User.objects.get(username=username)
    friend_request = FriendRequest.objects.get(sender= userid, receiver=request.user)
    if friend_request:
        friend_request.delete()
    userfriends = FriendList.objects.filter(user=request.user)
    friends = []
    if userfriends:
        for userfriend in userfriends:
            friends = userfriend.friends.all()
    friendrequest = FriendRequest.objects.filter(sender=request.user)
    recfriendrequest = FriendRequest.objects.filter(receiver=request.user)
    return render(request, 'accounts/friendlist.html', {'friends': friends, 'friendrequest':friendrequest, 'recfriendrequest':recfriendrequest})


def cancel(request, username):
    userid = User.objects.get(username=username)
    friend_request = FriendRequest.objects.get(sender= request.user, receiver=userid)
    if friend_request:
        friend_request.delete()
    userfriends = FriendList.objects.filter(user=request.user)
    friends = []
    if userfriends:
        for userfriend in userfriends:
            friends = userfriend.friends.all()
    friendrequest = FriendRequest.objects.filter(sender=request.user)
    recfriendrequest = FriendRequest.objects.filter(receiver=request.user)
    return render(request, 'accounts/friendlist.html', {'friends': friends, 'friendrequest':friendrequest, 'recfriendrequest':recfriendrequest})

templates/accounts/delete.html
{% extends "base.html" %}
{% block title %}Profile{% endblock %}
{% block content %}

<div class="container-fluid my-5">
    <section class="px-md-5 mx-md-5 text-center text-lg-left dark-grey-text">
        <div class="row d-flex justify-content-center">
            <div class="col-md-6">
                <form class="form-reset p-4 rounded update-form" action="{% url "accounts:deleteuser" %}" method="post">
                    {% csrf_token %}
                    <p class=" h5 mb-2 pt-4 font-weight-bold">Delete Account</p>
                    <p>Are you sure you want to delete your account?
                        *Important - your account data will remain available for 20 days</p>
                    <button type="submit" role="button"
                        class="btn btn-danger btn-block py-2 mb-4 mt-5 font-weight-bold">Delete</button>
                </form>
                <p class="small text-center pt-4">
                    <a href="{% url "accounts:profile" %}">Back to Dashboard</a>
                </p>
            </div>
        </div>
    </section>
</div>
{% endblock %}

templates/accounts/friend_requests.html
{% extends "base.html" %}
{% block title %}Friend Request{% endblock %}
{% block content %}
<div class="container">
    <p>Friend Requests</p>
</div>
{% endblock %}

templates/accounts/friendlist.html
{% extends "base.html" %}
{% block title %}Friend List{% endblock %}
{% block content %}
<div>
    <section>
        <div>
            <h1>Current Friends</h1>
            {% if friends %}
            <table class="table">
            <tbody>
            <tr>
            {% for friend in friends %}
                    <td>
                        <center>
                        <br>
                            <a href="/recommender/bestuserp/{{ friend }}">{{ friend }} </a><br/>
                            <img class="avatar" src="{{ friend.profile.avatar.url }}">
                        </center>
                    </td>
            {% endfor %}
            </tr>
            </tbody>
            </table>
            {% endif %}
            <br/>
            <br/>
            <br/>
            <br/>
            <h1>Sent Friend Request To:</h1>
            {% if friendrequest %}
            <table class="table">
            <tbody>
            <tr>
            {% for friend in friendrequest %}
                    <td>
                        <center>
                        <br>
                            <a href="/recommender/bestuserp/{{ friend }}">{{ friend.receiver }} </a>
                            <br/>
                            <br/>
                            <a class="btn btn-primary text-decoration-none" href="/account/cancel/{{friend.receiver}}">Cancel</a>
                        </center>
                    </td>
            {% endfor %}
            </tr>
            </tbody>
            </table>
            {% endif %}
            <br/>
            <br/>
            <br/>
            <br/>
            <h1>Recieved Friend Request From:</h1>
            {% if recfriendrequest %}
            <table class="table">
            <tbody>
            <tr>
            {% for friend in recfriendrequest %}
                    <td>
                        <center>
                        <br>
                            <a href="/recommender/bestuserp/{{ friend }}">{{ friend }} </a>
                            <br/>
                            <br/>
                            <a class="btn btn-primary text-decoration-none" href="/account/accept/{{friend}}">Accept</a>
                            <a class="btn btn-primary text-decoration-none ml-3" href="/account/decline/{{ friend }}">Decline</a>
                       </center>
                    </td>
            {% endfor %}
            </tr>
            </tbody>
            </table>
            {% endif %}
        </div>
    </section>
</div>
{% endblock %}

templates/accounts/profile.html
{% extends "base.html" %}
{% block title %}Profile{% endblock %}
{% block content %}
<style>
    .btn {
        position: relative;
        right: -380px;
    }

    .lead {
        position: relative;
        alignment: left;
        text-align: left;
    }

</style>
<div class="container container-fluid">
    <section class="jumbotron text-center bg-white">
        <div class="container container-fluid">
            <h1>{{ user.username}} Profile</h1>
            <img class="avatar" src="{{ user.profile.avatar.url }}">
            <div class="dropdown-divider"></div>
            <a class="btn btn-primary btn-lg text-decoration-none" href="{% url "accounts:edit" %}" type="edit">Edit</a>
            <br>
            <p class="lead text-muted list-inline">Username: &emsp; {{ user.username }}</p>
            <p class="lead text-muted">First Name: &emsp; {{ user.first_name }}</p>
            <p class="lead text-muted">Last Name: &emsp; {{ user.last_name }}</p>
            <p class="lead text-muted">Bio: &emsp; {{ user.profile.bio }}</p>
            <p class="lead text-muted">Friends: {{ numfriends }}</p>
                        {% if friends %}
            <table class="table">
            <tbody>
            <tr>
            {% for friend in friends %}
                    <td>
                        <center>
                        <br>
                            <a href="/recommender/bestuserp/{{ friend }}">{{ friend }} </a><br/>
                            <img class="avatar" src="{{ friend.profile.avatar.url }}">
                        </center>
                    </td>
            {% endfor %}
            </tr>
            </tbody>
            </table>
            {% endif %}
            <p class="lead text-muted">Playlists:</p>
            <br/>
            {% for playlist, songs, fav in playlists %}
                {% if playlist.is_public %}
            <div class="d-inline-flex p-2 ">
                <h2 class="">{{ playlist.title }}</h2>
                <span class=" pl-5 ml-5" id="like_count">
                    <h2>{{ playlist.like_count }}</h2></span>
                {% if request.user.is_authenticated %}
                    {% if fav %}
                        <a href="/recommender/playlistlikes/{{ playlist.id }}/F" class="text-decoration-none pt-2 pl-1">
                            <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="red" class="bi bi-heart-fill" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
                            </svg>
                        </a>
                    {% else %}
                        <a href="/recommender/playlistlikes/{{ playlist.id }}/T" class="text-decoration-none pt-2 pl-1 ">
                            <svg width="28" height="28" viewBox="0 0 16 16" class="bi bi-heart" fill="red" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                d="M8 2.748l-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z" />
                            </svg>
                        </a>
                    {% endif %}
                {% else %}
                <a href="{% url 'login' %}" class="text-decoration-none pt-2 pl-1">
                    <svg width="28" height="28" viewBox="0 0 16 16" class="bi bi-heart" fill="red" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                            d="M8 2.748l-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z" />
                    </svg>
                </a>
                {% endif %}
            </div>
            <br>
            <table class="table">
            <tbody>
            <tr>
                {% for song in songs %}
                    <td>
                        <center>
                        <iframe src="https://open.spotify.com/embed/track/{{ song.id }}" width="300" height="380" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
                        <br>
                        <a href="/recommender/playlistdelete/{{ playlist.id }}/{{ song.id }}">
                        </a>
                        </center>
                    </td>
                {% endfor %}
            </tr>
            </tbody>
            </table>
            <br>
            <br>
            <br>
                {% endif %}
            {% endfor %}
        </div>
    </section>
</div>
{% endblock %}

templates/accounts/sentrequest.html
{% extends 'base.html' %}
{% include 'friendlist.html' %}

templates/accounts/update.html
{% extends "base.html" %}
{% block title %}Profile{% endblock %}
{% block content %}
<style>
    .update-form input {
        border: 2px solid #ccc;
        height: calc(2em + .75rem + 2px);
    }

    .update-form input:focus {
        border-color: #1497ff;
        box-shadow: inset 0 0px 0px rgba(0, 0, 0, 0.075), 0 0 0px rgba(255, 0, 0, 0.6);
    }
</style>

<div class="container-fluid my-5">
    <section class="px-md-5 mx-md-5 text-center text-lg-left dark-grey-text">
        <div class="row d-flex justify-content-center">
            <div class="col-md-6">

                <form class="form-reset p-4 rounded update-form" method="post" enctype="multipart/form-data">

                    {% if user_form.is_valid and profile_form.is_valid %}
                    <div class="alert alert-primary" role="alert">
                        Details successfully updated!
                    </div>
                    <p class="small text-center pt-0">
                        <a href="{% url "accounts:profile" %}">Back to Dashboard</a>
                    </p>
                    {%else%}
                    <p class=" h4 mb-4 font-weight-bold">Change your details</p>
                    <p>You can edit your account using the following form:</p>
                    {% endif %}

                    {% if form.errors %}
                    <div class="alert alert-primary" role="alert">
                        Error: Please try again!
                    </div>
                    {% endif %}

                    {% if profile_form.errors %}
                    <div class="alert alert-primary" role="alert">
                        Error: Filesize incorrect - has to be 100px by 100px
                    </div>
                    {% endif %}

                    {% csrf_token %}
                    <label class="small font-weight-bold">{{ user_form.first_name.label}}</label>
                    {{ user_form.first_name }}
                    <label class="small font-weight-bold">{{ user_form.last_name.label}}</label>
                    {{ user_form.last_name }}
                    <label class="small font-weight-bold">{{ user_form.email.label}}</label>
                    {{ user_form.email }}
                    <label class="small font-weight-bold">{{ profile_form.bio.label}}</label>
                    {{ profile_form.bio }}
                    <div class="form-group pt-5">
                        <label class="small font-weight-bold">{{ profile_form.avatar.label}}</label>
                        {{ profile_form.avatar}}
                    </div>

                    <button class="btn btn-primary btn-block py-2 mb-4 mt-5 font-weight-bold" type="submit"
                        value="Save changes">Save Changes</button>
                    <hr class="mb-3">
                    <p class=" h5 mb-2 pt-4 font-weight-bold">Delete Account</p>
                    <p class="small">If you would like to delete your account press the button below:</p>
                    <a href="{% url "accounts:deleteuser" %}"
                        class="btn btn-danger btn-block py-2 mb-4 mt-5 font-weight-bold" role="button"
                        aria-pressed="true">Delete Account</a>
                </form>

            </div>
        </div>
    </section>
</div>
{% endblock %}