accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import UserLoginForm, PwdChangeForm


app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="registration/login.html",
                                                authentication_form=UserLoginForm), name='login'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.edit, name='edit'),
    path('profile/delete/', views.delete_user, name='deleteuser'),
    path('register/', views.accounts_register, name='register'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name="registration/password_change_form.html",
                                                                   form_class=PwdChangeForm), name='pwdforgot'),
    path('friendlist/', views.friendlist, name='friendlist'),
    path('sentrequest/<str:username>', views.sentrequest, name='sentrequest'),
    path('accept/<str:username>', views.accept, name='accept'),
    path('decline/<str:username>', views.decline, name='decline'),
    path('cancel/<str:username>', views.cancel, name='cancel'),
]

music/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('account/', include('django.contrib.auth.urls')),
    path('recommender/', include('recommender.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recommender/urls.py
from django.urls import path, include
from . import views

app_name = 'recommender'

urlpatterns = [
    path('home/', views.home, name='home'),
    path("",views.showslides),
    path('about/', views.about, name='about'),
    path('team/', views.about_team, name='team'),
    path('best/', views.searchform_get, name='best'),
    path('bestp/', views.searchform_post, name='bestp'),
    path('bestuser/', views.user_searchform_get, name='bestuser'),
    path('bestuserp/', views.user_searchform_post, name='bestuserp'),
    path('playlist/', views.playlist_get, name='playlist'),
    path('playlistb/', views.playlist_post, name='playlistb'),
    path('playlistaddb/<str:songid>/', views.playlistadd_post, name='playlistaddb'),
    path('playlist/<str:playlistid>/<str:songid>/', views.playlistadd_get, name='playlistadd'),
    path('playlistdelete/<str:playlistid>/<str:songid>/', views.playlistdeletesong, name='playlistdeletesong'),
    path('playlistdelete/<str:playlistid>/', views.playlistdelete, name='playlistdelete'),
    path('playlistpublic/<str:playlistid>/<str:public>', views.playlistpublic, name='playlistpublic'),
    path('bestuserp/<str:username>/', views.user_info, name='userinfo'),
    path('friendrequests', views.friend_request, name='friend_requests'),
    path('likes/<str:id>/<str:add>', views.like_list, name='like_list'),
    path('playlistlikes/<str:id>/<str:add>', views.playlistlike_list, name='playlistlike_list'),
    path('playlistlikesdelete/<str:id>', views.playlistlikedelete_list, name='playlistlikedelete_list'),
    path('likes/', views.profilelikes, name='likes'),
    path('searchbysong/', views.searchbysong_get, name='searchbysong'),
    path('searchbysongp/', views.searchbysong_post, name='searchbysongp')
    ]

templates/base.html
{% load static %}

<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>My search form</title>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    <link rel="shortcut icon" href="#">
</head>

<body>


    <!--Navbar-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/recommender/home">Home</a>
    <a class="navbar-brand" href="/recommender/about">About Us</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="False" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="/recommender/best">Search By Artist</a>
        </li>
      </ul>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="/recommender/searchbysong">Search By Song</a>
        </li>
      </ul>
    </div>
    <div class="collapse navbar-collapse" >
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="/recommender/bestuser">User Search</a>
          </li>
        </ul>
      </div>
    {% if request.user.is_authenticated %}

      <div class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="/account/friendlist">Friends</a>
          </li>
        </ul>
      </div>
        <a class="nav-link disabled" href="#">Welcome, {{user.username}}</a>

    <img class="avatar" src="
    {% for data in avatar %}
    {{ data.avatar.url }}
    {% endfor %}
    ">

    <ul class="navbar-nav">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url "accounts:profile" %}">Dashboard</a>
                <a class="dropdown-item" href="{% url "recommender:playlist" %}">Playlist</a>
                <a class="dropdown-item" href="{% url "recommender:likes" %}">Likes</a>
                <a class="dropdown-item" href="{% url "accounts:edit" %}">Edit details</a>
                <a class="dropdown-item" href="{% url "password_change" %}">Change Password</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url "logout" %}">Logout</a>
            </div>
        </li>
    </ul>
    {% else %}
    <nav>
        <ul class="navbar-nav mr-auto">
            <a class="nav-link" href="{% url "accounts:register" %}">Register</a>
            <a class="nav-link" href="{% url "login" %}">Login</a>
        </ul>
    </nav>
    {% endif %}
  </nav>

    <div class="container">
        <br>
        <br>
        {% block content %}
        {% endblock %}
    </div>
</body>
<style>
    .avatar {
        height: 30px;
        width: 30px;
        background-color: #000;
        border-radius: 50%;
        display: inline-block;
    }
</style>